### ISSUE TITLE
flake: unpin catppuccin input

### ISSUE THREAD

**Issue by britter** [britter/nix-configuration#31]
catppuccin/nix needed to be pinned to a specific commit due to https://github.com/catppuccin/nix/issues/154. Once Home manager 24.05 is released, this can be rolled back.

**Comment by sokai** [comment]
*J*FYI: it seems to be [fixed](https://github.com/catppuccin/nix/pull/182) :)

*#unpintime* KR

**Comment by britter** [comment]
@sokai thanks for the pointer. This is great!
